stages:
  - build
  - test

build:
  stage: build
  script:
    - docker --version
    - docker ps -a
    - docker-compose build
    - docker-compose up -d  # Start the containers in detached mode

test_api:
  stage: test
  script:
    # Ensure the containers are up
    - docker-compose ps
    # Run the bash script to test the API
    - bash test_api.sh
  after_script:
    # Shut down the containers after tests are done
    - docker-compose down