stages:
  - build
  - test

build:
  stage: build
  script:
    - docker --version
    - docker ps -a
    - docker-compose build
    - docker-compose up -d  # Start the containers for test

test_api:
  stage: test
  script:
    # Ensure the containers are up
    - docker-compose ps
    # Run the bash script to test the API
    - bash test/test_api.sh
  after_script:
    # Shut down the containers after tests are done
    - docker-compose down

deploy:
stage: deploy
  script:
    # Deploy to local machine (just bring up the containers again)
    - echo "Deploying to local machine..."
    - docker-compose up -d  
  only:
    # deploy only on main branch update, assuming that others may not be ready to be deployed
    - main