image: docker:latest

services:
  - name: docker:latest
    alias: docker

variables:
  DOCKER_HOST: unix:///var/run/docker.sock

stages:
  - build

build:
  stage: build
  script:
    - docker --version
    - docker-compose -f docker-compose.yaml build
