
services:
  service1:
    build: ./service1
    deploy:
      replicas: 3
    ports:
      - "8199"
    depends_on:
      - service2
    networks:
      - internal
    environment:
      - SLEEP_DURATION=2

  service2:
    build: ./service2
    expose:
      - "8200"
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:latest
    ports:
      - "8198:80" 
    networks:
      - internal
    depends_on: 
      - service1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/auth.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/index.html:/usr/share/nginx/html/index.html

networks:
  internal:
    