version: '3'
services:
  service1:
    build: ./service1
    ports:
      - "8199:8199"
    depends_on:
      - service2
    networks:
      - internal
  service2:
    build: ./service2
    expose:
      - "8200"
    networks:
      - internal

networks:
  internal:
    